# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7bc43f907d25c6d8b0b0dd4b7fbdb9101c5e223864f24dff90e06c6918de969aff02ab8264a69ca2371d1a7319ae8845054bb46b061183ff1a5eda4c9edf887a

test:
  secret_key_base: 68c4bdae0a7e892b181934a11c837859a3a871f5501a4867dd3627d9096ca2a4e1fd3d255640523d56a2a315b831fed2269c836760c4d375c9118e721ff6d03f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
